services:
  - type: web # On change "static" par "web"
    name: jehobless-prestige
    env: static # L'environnement reste bien "static"
    buildCommand: "" 
    staticPublishPath: "."
    pullRequestPreviewsEnabled: true
